version: '3.8'

services:
  api-gateway:
    build:
      context: .
      dockerfile: ./apps/api-gateway/Dockerfile
      target: development
    environment:
      - NODE_ENV=development
    volumes:
      - ./apps/api-gateway/src:/usr/src/app/apps/api-gateway/src
      - ./libs/shared-types/src:/usr/src/app/libs/shared-types/src
      - ./apps/api-gateway/nodemon.json:/usr/src/app/apps/api-gateway/nodemon.json
      - ./nest-cli.json:/usr/src/app/nest-cli.json
      - ./tsconfig.json:/usr/src/app/tsconfig.json
      - /usr/src/app/node_modules
      - ./dist:/usr/src/app/dist

  users:
    build:
      context: .
      dockerfile: ./apps/users/Dockerfile
      target: development
    environment:
      - NODE_ENV=development
    volumes:
      - ./apps/users/src:/usr/src/app/apps/users/src
      - ./libs/shared-types/src:/usr/src/app/libs/shared-types/src
      - ./apps/users/nodemon.json:/usr/src/app/apps/users/nodemon.json
      - ./nest-cli.json:/usr/src/app/nest-cli.json
      - ./tsconfig.json:/usr/src/app/tsconfig.json
      - /usr/src/app/node_modules
      - dist:/usr/src/app/dist

  orders:
    build:
      context: .
      dockerfile: ./apps/orders/Dockerfile
      target: development
    environment:
      - NODE_ENV=development
    volumes:
      - ./apps/orders/src:/usr/src/app/apps/orders/src
      - ./libs/shared-types/src:/usr/src/app/libs/shared-types/src
      - ./apps/orders/nodemon.json:/usr/src/app/apps/orders/nodemon.json
      - ./nest-cli.json:/usr/src/app/nest-cli.json
      - ./tsconfig.json:/usr/src/app/tsconfig.json
      - /usr/src/app/node_modules
      - dist:/usr/src/app/dist

  payments:
    build:
      context: .
      dockerfile: ./apps/payments/Dockerfile
      target: development
    environment:
      - NODE_ENV=development
    volumes:
      - ./apps/payments/src:/usr/src/app/apps/payments/src
      - ./libs/shared-types/src:/usr/src/app/libs/shared-types/src
      - ./apps/payments/nodemon.json:/usr/src/app/apps/payments/nodemon.json
      - ./nest-cli.json:/usr/src/app/nest-cli.json
      - ./tsconfig.json:/usr/src/app/tsconfig.json
      - /usr/src/app/node_modules
      - dist:/usr/src/app/dist

volumes:
  dist: